#PINN隐藏层：通常使用5到20个节点
#浅层网络：1到3层，适用于简单问题。
#中等深度：4到10层，适用于中等复杂度的问题。
#深层网络：10层以上，适用于更复杂的方程和高维问题。

exp1:
  CNT: 1  # 实验总轮数
  layers: [5, 5]

exp2:
  CNT: 1  # 实验总轮数
  layers: [5, 5, 5, 5, 5, 5]

exp3:
  CNT: 1
  layers: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


exp4:
  CNT: 1
  layers: [10, 10]

exp5:
  CNT: 1
  layers: [10, 10, 10, 10, 10, 10]
exp6:
  CNT: 1
  layers: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]

exp7:
  CNT: 1
  layers: [18, 18]

exp8:
  CNT: 1
  layers: [18, 18, 18, 18, 18, 18]
exp9:
  CNT: 1
  layers: [18, 18, 18, 18, 18, 18, 18, 18, 18, 18]

