exp1:
  CNT: 100
  layers: [2, 2]

exp2:
  CNT: 100
  layers: [4, 4]

exp3:
  CNT: 100
  layers: [8, 8]

exp4:
  CNT: 100
  layers: [16, 16]
exp5:
  CNT: 100
  layers: [2, 2, 2, 2]
exp6:
  CNT: 100
  layers: [4, 4, 4, 4]
exp7:
  CNT: 100
  layers: [8, 8, 8, 8]

exp8:
  CNT: 100
  layers: [16, 16, 16, 16]

exp9:
  CNT: 100
  layers: [2, 2, 2, 2, 2, 2, 2, 2]

exp10:
  CNT: 100
  layers: [4, 4, 4, 4, 4, 4, 4, 4]

exp11:
  CNT: 100
  layers: [8, 8, 8, 8, 8, 8, 8, 8]
exp12:
  CNT: 100
  layers: [16, 16, 16, 16, 16, 16, 16, 16]